# Generated by Django 4.1.3 on 2022-11-14 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0002_category_alter_services_options_services_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cle_en_main_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Cle en main category',
                'verbose_name_plural': 'Cle en main categories',
                'ordering': ['id'],
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='Service_cat',
        ),
        migrations.AlterModelOptions(
            name='service_cat',
            options={'ordering': ['id'], 'verbose_name': 'Category of services', 'verbose_name_plural': 'Categories of services'},
        ),
        migrations.CreateModel(
            name='Cle_en_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('icon', models.ImageField(upload_to='icons/%Y/%m/%d')),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='avangard.cle_en_main_cat')),
            ],
            options={
                'verbose_name': 'Cle en main',
                'verbose_name_plural': 'Cle en main',
                'ordering': ['title'],
            },
        ),
    ]
