# Generated by Django 4.1.3 on 2022-11-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0007_alter_cle_en_main_icon_alter_services_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cle_en_main_cat',
            options={'ordering': ['id'], 'verbose_name': 'Categorie des cle en main', 'verbose_name_plural': 'Categories des cle en main'},
        ),
        migrations.AlterModelOptions(
            name='service_cat',
            options={'ordering': ['id'], 'verbose_name': 'Categorie des services', 'verbose_name_plural': 'Categories des services'},
        ),
        migrations.AddField(
            model_name='cle_en_main_cat',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cle_en_main_cat',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='service_cat',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
