# Generated by Django 4.1.3 on 2022-11-23 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0008_alter_cle_en_main_cat_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
