# Generated by Django 4.1.3 on 2022-11-27 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0009_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cle_en_main',
            name='cle_en_main_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avangard.cle_en_main_cat'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avangard.service_cat'),
        ),
    ]
