# Generated by Django 4.1.3 on 2022-11-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0015_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='phone',
            field=models.CharField(db_index=True, default=1, max_length=255),
            preserve_default=False,
        ),
    ]
