# Generated by Django 4.1.3 on 2022-12-03 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avangard', '0017_alter_personal_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='current_orders',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Commandes en cours'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='email',
            field=models.EmailField(max_length=255, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='favourite',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Les favoris'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='order_history',
            field=models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Historique de commandes'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='phone',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Numero de telephone'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='settings',
            field=models.CharField(blank=True, max_length=255, verbose_name='Parametres de profil'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='user',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nom'),
        ),
    ]
