# Generated by Django 4.1.3 on 2022-12-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0019_rename_user_personal_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['id'], 'verbose_name': 'Personal', 'verbose_name_plural': 'Personal'},
        ),
        migrations.AddField(
            model_name='personal',
            name='password1',
            field=models.CharField(default=1, max_length=255, verbose_name='Mot de passe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personal',
            name='password2',
            field=models.CharField(default=1, max_length=255, verbose_name='Mot de passe confirmer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personal',
            name='username',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nom'),
        ),
    ]
