# Generated by Django 4.1.4 on 2022-12-26 14:51

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=255, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Nom')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('phone', models.CharField(db_index=True, max_length=255, verbose_name='Numero de telephone')),
                ('password1', models.CharField(max_length=255, verbose_name='Mot de passe')),
                ('password2', models.CharField(max_length=255, verbose_name='Mot de passe confirmer')),
                ('current_orders', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Commandes en cours')),
                ('order_history', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Historique de commandes')),
                ('favourite', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Les favoris')),
                ('settings', models.CharField(blank=True, max_length=255, verbose_name='Parametres de profil')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Categorie des services',
                'verbose_name_plural': 'Categories des services',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/%Y/%m/%d')),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('service_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avangard.service_cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Cle_en_main_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Categorie des cle en main',
                'verbose_name_plural': 'Categories des cle en main',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Cle_en_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/%Y/%m/%d')),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('cle_en_main_cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avangard.cle_en_main_cat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Cle en main',
                'verbose_name_plural': 'Cle en main',
                'ordering': ['title'],
            },
        ),
    ]
