# Generated by Django 4.1.3 on 2022-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0004_remove_cle_en_main_cat_remove_services_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_cat',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
