# Generated by Django 4.1.3 on 2022-11-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0011_cle_en_main_user_cle_en_main_cat_user_service_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cle_en_main',
            name='user',
        ),
        migrations.RemoveField(
            model_name='cle_en_main_cat',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service_cat',
            name='user',
        ),
    ]
