# Generated by Django 4.1.3 on 2022-11-28 17:35

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0013_cle_en_main_user_cle_en_main_cat_user_service_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(db_index=True, max_length=255, verbose_name=django.contrib.auth.models.User)),
                ('current_orders', models.CharField(blank=True, db_index=True, max_length=255)),
                ('order_history', models.CharField(blank=True, db_index=True, max_length=255)),
                ('favourite', models.CharField(blank=True, db_index=True, max_length=255)),
                ('settings', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personals',
                'ordering': ['id'],
            },
        ),
    ]
