# Generated by Django 4.1.3 on 2022-12-03 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avangard', '0018_alter_personal_current_orders_alter_personal_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personal',
            old_name='user',
            new_name='username',
        ),
    ]
